# Appveyor Configuration File
# See http://www.appveyor.com/docs/appveyor-yml for many more options

# version
version: 1.0.0.{build}

#Variables
# Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: 73/lsdBR/7wiaovlC3GnhcQbOEqaM+zAC8dU+91JRwW70GZwNX2leai+tmrlGyPN

before_build:
  - ps: Write-Host "Build version :`  $env:APPVEYOR_BUILD_VERSION"
  - ps: Write-Host "Branch        :`  $env:APPVEYOR_REPO_BRANCH"

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build\build.ps1